"""unique constraint to user_id on instructor table

Revision ID: 957f3789aab3
Revises: 0c8719a84b44
Create Date: 2023-12-10 17:05:52.689391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957f3789aab3'
down_revision = '0c8719a84b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_user_id", ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.drop_constraint("unique_user_id", type_='unique')

    # ### end Alembic commands ###
