"""add is_admin to user table

Revision ID: acd3b3c9c68c
Revises: 7c83b720e531
Create Date: 2023-12-08 16:00:04.967190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acd3b3c9c68c"
down_revision = "7c83b720e531"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_admin", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_admin")

    # ### end Alembic commands ###
