"""create subject table

Revision ID: f05362e024b3
Revises: acd3b3c9c68c
Create Date: 2023-12-09 13:26:16.622181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f05362e024b3"
down_revision = "acd3b3c9c68c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descriptive_title", sa.String(length=64), nullable=False),
        sa.Column("course_number", sa.String(length=32), nullable=False),
        sa.Column("lec_hours", sa.Integer(), nullable=False),
        sa.Column("lab_hours", sa.Integer(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_number"),
        sa.UniqueConstraint("descriptive_title"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subject")
    # ### end Alembic commands ###
